name = "nuxt-prepare"
compatibility_date = "2025-09-01"
routes = [ { pattern = "nuxt-prepare.byjohann.dev", custom_domain = true } ]

[assets]
directory = "./docs/.vitepress/dist/"
not_found_handling = "404-page"
